call_parentheses          = "Always"
collapse_simple_statement = "Never"
column_width              = 120
indent_type               = "Spaces"
indent_width              = 4
quote_style               = "AutoPreferDouble"
syntax                    = "Lua51"

[sort_requires]
enabled = true
